name: Gulp CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Gulp tasks (Minify & Test)
        run: npx gulp

      - name: Commit and push files
        run: |
          git config user.name 'liledix4[bot]'
          git config user.email '195217104+liledix4[bot]@users.noreply.github.com'
          git commit -a -m "🤖 Updated output files"
          git push